Option --no-color is unknonw
The `--no-color` option no longer exist (newman --version : 4.5.7)

```
newman run mycollection.json --data data.json --no-color
error: unknown option '--no-color'
```
Should use the `--color <value>` as specified in newman's help :
```
$ newman run --help | grep "color"
--color <value>                 Enable/Disable colored output. (auto|on|off) (default: "auto")
```