Option --data [file] is unknown
The `--data` option doesn't exist (newman --version : 4.5.7)

```bash
$ newman run mycollection.json --data data.json
error: unknown option '--data'
```

Works well with `--iteration-data` as specified in the help of newman :
```
$ newman run --help |grep "data file"
  -d, --iteration-data <path>     Specify a data file to use for iterations (either json or csv).
```